### ISSUE TITLE
发送formData格式时，content-type被转换为application/x-www-form-urlencoded导致无法上传文件

### ISSUE THREAD

**Issue by huanghaiyang** [winixt/request#2]
![image](https://github.com/winixt/request/assets/5448818/7d1b835d-97f8-4cb3-bcd5-68fb1506b809)
![image](https://github.com/winixt/request/assets/5448818/46e8afc1-9380-4ba3-a599-3eb001bda28c)
期望
![image](https://github.com/winixt/request/assets/5448818/0aa9fad2-091a-4309-91e8-859dcac0940f)
![image](https://github.com/winixt/request/assets/5448818/a58e9369-9261-49dc-b786-8f75dfea87ab)

**Comment by winixt** [comment]
@huanghaiyang 升级到 0.1.7
